global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # prometheus itself

  # scrape host metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.36.59:9100']

  # scrape container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] # Uses docker's internal DNS